version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: proform-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: durak123
      POSTGRES_DB: ProFormDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: [
      '-c', 'max_connections=200',
      '-c', 'shared_buffers=1GB',
      '-c', 'effective_cache_size=4GB'
    ]